# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160404_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_status',
        ),
    ]
