# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_auth_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photoUrl',
            field=models.ImageField(default=b'heads/default.jpg', upload_to=b'heads/%Y/%m/%d'),
        ),
    ]
