# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=b'', max_length=250)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
