# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('music_id', models.IntegerField(default=0)),
                ('comment', models.CharField(default=b'', max_length=250)),
                ('time', models.DateTimeField(default=0)),
            ],
        ),
    ]
