# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20160410_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
