# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('collects', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=0)),
                ('album', models.CharField(default=b'', max_length=100)),
                ('singer', models.CharField(default=b'', max_length=100)),
                ('photoUrl', models.CharField(blank=True, max_length=100)),
                ('mediaUrl', models.CharField(blank=True, max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Language')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Style')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Theme')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
