# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('language', models.CharField(default=b'', max_length=100)),
                ('style', models.CharField(default=b'', max_length=100)),
                ('theme', models.CharField(default=b'', max_length=100)),
                ('collects', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('time', models.BigIntegerField(default=0)),
            ],
        ),
    ]
