# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('language', models.CharField(default=b'', max_length=100)),
                ('style', models.CharField(default=b'', max_length=100)),
                ('theme', models.CharField(default=b'', max_length=100)),
                ('collects', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=0)),
                ('album', models.CharField(default=b'', max_length=100)),
                ('singer', models.CharField(default=b'', max_length=100)),
                ('photoUrl', models.CharField(blank=True, max_length=100)),
                ('mediaUrl', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
