# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='mediaUrl',
            field=models.FileField(upload_to=b'musics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='music',
            name='photoUrl',
            field=models.ImageField(upload_to=b'photos/%Y/%m/%d'),
        ),
    ]
