# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20160328_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='mediaUrl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
