# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='collects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setlist',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
