# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0002_auto_20160411_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='singer',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
