# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0002_auto_20160427_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='info',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
