# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('music_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
