# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='setlist_id',
            field=models.IntegerField(default=0),
        ),
    ]
