# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20160410_2145'),
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetlistMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.Music')),
            ],
        ),
        migrations.RemoveField(
            model_name='setlist',
            name='music',
        ),
        migrations.AddField(
            model_name='setlistmusic',
            name='setlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setlists.Setlist'),
        ),
        migrations.AddField(
            model_name='setlist',
            name='musics',
            field=models.ManyToManyField(through='setlists.SetlistMusic', to='musics.Music'),
        ),
    ]
